// Package compiler 确定性编译器: Fact Graph → OpenAPI 3.1
// （设计文档 §8 八阶段流水线 + §8.5 序列化规范）。
//
// 核心承诺: 相同输入 → 逐字节相同的 YAML。
package compiler

import (
	"fmt"
	"sort"
	"strings"

	"github.com/specforge/specforge/internal/codegraph"
	"github.com/specforge/specforge/internal/facts"
	"github.com/specforge/specforge/internal/typeschema"
)

// Input 编译输入。
type Input struct {
	ServiceName string
	Framework   string
	Facts       []*facts.Fact
	Schemas     map[string]*typeschema.Schema
	Graph       *codegraph.Graph
}

// Document 编译产物（结构化中间形态，供渲染器消费）。
type Document struct {
	Title       string
	Version     string
	Description string
	Framework   string
	Operations  []Operation // 稳定排序
	Schemas     []NamedSchema
	SecSchemes  []SecScheme
}

// Operation 一个 operation 的最终形态。
type Operation struct {
	Method      string
	Path        string
	OperationID string
	Summary     string
	Description string
	Tags        []string
	Params      []ParamOut
	Body        *BodyOut
	Responses   []ResponseOut
	Security    []string
	Confidence  float64
	Unknowns    []string
	Evidence    []string
	Stale       bool
}

// ParamOut 输出参数。
type ParamOut struct {
	Name     string
	In       string
	Required bool
	Type     string
	Format   string
	Origin   string
}

// BodyOut 请求体。
type BodyOut struct {
	ContentType string
	SchemaName  string // $ref 名
}

// ResponseOut 响应行。
type ResponseOut struct {
	Status        string
	Codes         []int  // 信封码集合（enum）
	HasUnresolved bool   // 是否存在未解析的错误行
	Description   string // 聚合描述
	SchemaName    string // 信封 data 槽的 $ref 名（空 = 无 body）
	ArrayElem     string // 切片响应: data 为 array，元素 $ref 名
	HasBody       bool
	MapValueType  string // map[K]V 响应: data 为 additionalProperties map，值类型
	Sinks         []string
}

// NamedSchema 命名 schema。
type NamedSchema struct {
	Name   string
	TypeID string
	Schema *typeschema.Schema
	Shape  string // shapeHash（去重分组键）
}

// SecScheme 安全方案。
type SecScheme struct {
	Name       string
	Type       string
	In         string
	HeaderName string
	Required   bool
	ScopeArg   string
}

// Compile 执行编译流水线（Stage 3–7 的 P0 形态）。
func Compile(in Input) (*Document, error) {
	d := &Document{
		Title:     in.ServiceName + " API",
		Version:   "1.0.0",
		Framework: in.Framework,
		Description: "Generated by specforge from source code. " +
			"Every field is evidence-traceable; unresolved items are marked x-specforge-unknown.",
	}

	// ---- Stage 3: 事实合并（P0 单来源 static，直接索引化） ----
	contractByOp := map[string]*facts.ContractPayload{}
	enrichByOp := map[string]facts.EnrichmentPayload{}
	var secFacts []*facts.SecurityPayload
	var schemaFacts map[string]*typeschema.Schema = in.Schemas
	for _, f := range in.Facts {
		switch f.Kind {
		case facts.KindContract:
			if cp, ok := f.Value.(facts.ContractPayload); ok {
				contractByOp[f.ID] = &cp
			} else if cpp, ok := f.Value.(*facts.ContractPayload); ok {
				contractByOp[f.ID] = cpp
			}
		case facts.KindEnrichment:
			if ep, ok := f.Value.(facts.EnrichmentPayload); ok {
				enrichByOp[strings.TrimSuffix(f.ID, ":enrich")] = ep
			}
		case facts.KindSecurity:
			if sp, ok := f.Value.(facts.SecurityPayload); ok {
				spc := sp
				secFacts = append(secFacts, &spc)
			}
		case facts.KindSchema:
			if s, ok := f.Value.(*typeschema.Schema); ok {
				if schemaFacts == nil {
					schemaFacts = map[string]*typeschema.Schema{}
				}
				schemaFacts[strings.TrimPrefix(f.ID, "schema:")] = s
			}
		}
	}

	// ---- Stage 4: Schema 图（$ref 命名 + 去重） ----
	var refOf map[string]string
	d.Schemas, refOf = nameAndDedupe(in, schemaFacts)

	// ---- Stage 5: operation 组装 ----
	for opKey, cp := range contractByOp {
		method, path := splitOpKey(opKey)
		op := Operation{
			Method: method, Path: path,
			OperationID: cp.OperationID,
			Tags:        cp.Tags,
		}
		if ep, ok := enrichByOp[strings.TrimPrefix(opKey, "contract:")]; ok {
			op.Summary = ep.Summary
			op.Description = ep.Description
		}
		// 参数（稳定排序: in 权重 + name）
		for _, p := range cp.Params {
			op.Params = append(op.Params, ParamOut{
				Name: p.Name, In: p.In, Required: p.Required,
				Type: p.Type, Format: p.Format, Origin: p.Origin,
			})
		}
		sortParams(op.Params)
		// 请求体
		if cp.RequestBody != nil {
			if ref, ok := refOf[cp.RequestBody.SchemaType]; ok {
				op.Body = &BodyOut{ContentType: cp.RequestBody.ContentType, SchemaName: ref}
			} else {
				op.Unknowns = append(op.Unknowns, "request schema not synthesized: "+cp.RequestBody.SchemaType)
			}
		}
		// 响应矩阵 → 按 status 分组合并（OpenAPI responses 是 status 唯一映射，
		// 信封码集合进 code enum —— 设计文档 §4.2 的编译形态）
		respGroups := map[string]*ResponseOut{}
		var respOrder []string
		for _, r := range cp.Responses {
			st := fmt.Sprintf("%d", r.Status)
			g := respGroups[st]
			if g == nil {
				g = &ResponseOut{Status: st, HasBody: r.HasBody}
				respGroups[st] = g
				respOrder = append(respOrder, st)
			}
			code, msg := -1, ""
			if r.Envelope != nil {
				code, msg = r.Envelope.Code, r.Envelope.Msg
			}
			if code == 0 {
				g.Description = appendDesc(g.Description, "Success (code=0)")
			} else if code > 0 {
				g.Description = appendDesc(g.Description,
					fmt.Sprintf("Business error (code=%d): %s", code, msg))
			} else {
				g.HasUnresolved = true
				desc := "Business error (code unresolved from source)"
				if r.Envelope != nil && r.Envelope.Msg != "" {
					desc = "Business error (code unresolved from source; " + r.Envelope.Msg + ")"
				}
				g.Description = appendDesc(g.Description, desc)
			}
			if code >= 0 {
				g.Codes = appendUniq(g.Codes, code)
			}
			if r.SchemaType != "" {
				if strings.HasPrefix(r.SchemaType, "[]") {
					// 切片响应: data = array + items $ref
					elem := strings.TrimPrefix(r.SchemaType, "[]")
					if ref, ok := refOf[elem]; ok {
						g.ArrayElem = ref
						g.HasBody = true
					} else {
						op.Unknowns = append(op.Unknowns, "response schema not synthesized: "+r.SchemaType)
					}
				} else if ref, ok := refOf[r.SchemaType]; ok {
					g.SchemaName = ref
					g.HasBody = true
				} else {
					op.Unknowns = append(op.Unknowns, "response schema not synthesized: "+r.SchemaType)
				}
			}
			if r.MapValueType != "" {
				g.MapValueType = r.MapValueType
				g.HasBody = true
			}
			if r.Sink != "" && r.Sink != "(multiple)" {
				g.Sinks = appendUniqStr(g.Sinks, r.Sink)
			}
		}
		sort.Strings(respOrder)
		for _, st := range respOrder {
			g := respGroups[st]
			sort.Ints(g.Codes)
			op.Responses = append(op.Responses, *g)
		}
		// security（来自该 operation 的中间件链，设计文档 F7）
		op.Security = cp.Security
		// 置信度: contract 事实的 confidence（由 engine 计算）
		for _, f := range in.Facts {
			if f.ID == opKey {
				op.Confidence = f.Confidence
			}
		}
		d.Operations = append(d.Operations, op)
	}

	// ---- Stage 7: 规范化排序 ----
	sort.Slice(d.Operations, func(i, j int) bool {
		a, b := d.Operations[i], d.Operations[j]
		if a.Path != b.Path {
			return pathLess(a.Path, b.Path)
		}
		return methodOrder(a.Method) < methodOrder(b.Method)
	})
	sort.Slice(d.Schemas, func(i, j int) bool { return d.Schemas[i].Name < d.Schemas[j].Name })
	sort.Slice(secFacts, func(i, j int) bool {
		return secFacts[i].MiddlewareSymbol < secFacts[j].MiddlewareSymbol
	})
	seenScheme := map[string]bool{}
	for _, sp := range secFacts {
		name := sp.MiddlewareSymbol
		if i := strings.LastIndex(name, "."); i >= 0 {
			name = name[i+1:]
		}
		if sp.Header != "" {
			name = sp.Header
		}
		if seenScheme[name] {
			continue
		}
		seenScheme[name] = true
		d.SecSchemes = append(d.SecSchemes, SecScheme{
			Name: name, Type: schemeTypeOf(sp), In: "header",
			HeaderName: sp.Header, Required: sp.Required, ScopeArg: sp.ScopeArg,
		})
	}
	d.Title = in.ServiceName + " API"
	return d, nil
}

// nameAndDedupe §8.3 $ref 命名与去重（shapeHash 分组）。
//
// 分组策略：完全同 shape 的多个 typeID 归入同一组，组内选一个最简名作为 $ref 名，
// 其余 typeID 全部映射到该 $ref 名。这与「结构去重」的初衷一致——
// 完全同构的类型只 emit 一份 schema。纯启发式（描述字段从 shape 剔除，仅比较结构）。
// 返回 (NamedSchema 列表, typeID→$ref 名映射)。
func nameAndDedupe(in Input, schemas map[string]*typeschema.Schema) ([]NamedSchema, map[string]string) {
	type group struct {
		typeIDs []string
		shape   string
	}
	groups := map[string]*group{}
	for id, sc := range schemas {
		shape := canonicalShape(sc)
		g := groups[shape]
		if g == nil {
			g = &group{shape: shape}
			groups[shape] = g
		}
		g.typeIDs = append(g.typeIDs, id)
	}
	// 组内选「最简类型名」，组间冲突加包名，仍冲突加 shapeHash 前缀
	byName := map[string]bool{}
	refOf := map[string]string{}
	var out []NamedSchema
	for _, g := range groups {
		sort.Strings(g.typeIDs)
		primary := g.typeIDs[0]
		name := lastSeg(primary)
		if byName[name] {
			name = pkgShort(primary) + "." + lastSeg(primary)
		}
		if byName[name] {
			name = lastSeg(primary) + "-" + shortHash(g.shape)
		}
		byName[name] = true
		out = append(out, NamedSchema{Name: name, TypeID: primary, Schema: schemas[primary], Shape: g.shape})
		// 组内全部 typeID 映射到同一 $ref 名（含非 primary 的 typeID）。
		for _, id := range g.typeIDs {
			refOf[id] = name
		}
	}
	return out, refOf
}

// canonicalShape schema 的规范化结构签名（去重键，不含描述性字段）。
func canonicalShape(sc *typeschema.Schema) string {
	var b strings.Builder
	writeShape(&b, sc, 0)
	return b.String()
}

func writeShape(b *strings.Builder, sc *typeschema.Schema, depth int) {
	if sc == nil || depth > 24 {
		b.WriteString("#")
		return
	}
	if sc.Ref != "" {
		b.WriteString("ref:" + sc.Ref)
		return
	}
	fmt.Fprintf(b, "t:%s;f:%s;nb:%v;n:%v;ad:%v;", sc.Type, sc.Format, sc.NoBody, sc.Nullable, sc.Additional)
	if len(sc.Enum) > 0 {
		b.WriteString("e:" + strings.Join(sc.Enum, "|") + ";")
	}
	if sc.Min != nil {
		fmt.Fprintf(b, "min:%v;", *sc.Min)
	}
	if sc.Max != nil {
		fmt.Fprintf(b, "max:%v;", *sc.Max)
	}
	if sc.MinLen != nil {
		fmt.Fprintf(b, "ml:%v;", *sc.MinLen)
	}
	if sc.MaxLen != nil {
		fmt.Fprintf(b, "xl:%v;", *sc.MaxLen)
	}
	for _, p := range sc.Props {
		fmt.Fprintf(b, "p:%s;req:%v;", p.Name, p.Required)
		writeShape(b, p.Schema, depth+1)
		if sc.Items != nil {
			writeShape(b, sc.Items, depth+1)
		}
		for _, p := range sc.Props {
			fmt.Fprintf(b, "p:%s;req:%v;", p.Name, p.Required)
			writeShape(b, p.Schema, depth+1)
		}
	}
}

func shortHash(s string) string {
	// FNV 快速哈希（P0 简化; P1 换 sha256 截断）
	var h uint64 = 14695981039346656037
	for i := 0; i < len(s); i++ {
		h ^= uint64(s[i])
		h *= 1099511628211
	}
	return fmt.Sprintf("%06x", h&0xffffff)
}

// ---- 渲染入口（供 CLI 调用） --------------------------------------------

// CompileTwiceCheck 确定性双跑自检（设计文档 §8.5）:
// 对同一 Document 渲染两次，逐字节比对。
func CompileTwiceCheck(doc *Document) bool {
	y1, err1 := RenderYAML(doc)
	y2, err2 := RenderYAML(doc)
	if err1 != nil || err2 != nil {
		return false
	}
	return string(y1) == string(y2)
}

// RenderYAML 输出最终 YAML 文本。
func RenderYAML(d *Document) ([]byte, error) {
	return render(d)
}

// ---- 辅助 --------------------------------------------------------------

func splitOpKey(opKey string) (method, path string) {
	// 兼容 "contract:op:METHOD:/path" 与 "op:METHOD:/path"
	s := strings.TrimPrefix(opKey, "contract:")
	s = strings.TrimPrefix(s, "op:")
	if i := strings.Index(s, ":"); i > 0 {
		return s[:i], s[i+1:]
	}
	return "", s
}

func sortParams(ps []ParamOut) {
	sort.Slice(ps, func(i, j int) bool {
		a, b := ps[i], ps[j]
		if inOrder(a.In) != inOrder(b.In) {
			return inOrder(a.In) < inOrder(b.In)
		}
		return a.Name < b.Name
	})
}

func inOrder(in string) int {
	switch in {
	case "path":
		return 0
	case "query":
		return 1
	case "header":
		return 2
	case "cookie":
		return 3
	}
	return 4
}

func methodOrder(m string) int {
	switch strings.ToLower(m) {
	case "get":
		return 0
	case "put":
		return 1
	case "post":
		return 2
	case "delete":
		return 3
	case "patch":
		return 4
	case "head":
		return 5
	case "options":
		return 6
	}
	return 9
}

// pathLess 路径分段字典序（设计文档 §8.5 规则 2）。
func pathLess(a, b string) bool {
	as := strings.Split(strings.TrimPrefix(a, "/"), "/")
	bs := strings.Split(strings.TrimPrefix(b, "/"), "/")
	for i := 0; i < len(as) && i < len(bs); i++ {
		if as[i] != bs[i] {
			return as[i] < bs[i]
		}
	}
	return len(as) < len(bs)
}

func lastSeg(s string) string {
	if i := strings.LastIndex(s, "."); i >= 0 {
		return s[i+1:]
	}
	return s
}

func pkgShort(typeID string) string {
	if i := strings.LastIndex(typeID, "/"); i >= 0 {
		return typeID[i+1:]
	}
	return typeID
}

func schemeTypeOf(sp *facts.SecurityPayload) string {
	switch sp.SchemeType {
	case "apiKey":
		return "apiKey"
	case "http":
		return "http"
	case "bearer":
		return "http"
	}
	return "apiKey"
}

func containsStr(s []string, v string) bool {
	for _, x := range s {
		if x == v {
			return true
		}
	}
	return false
}

func appendDesc(base, add string) string {
	if base == "" {
		return add
	}
	return base + "; " + add
}

func appendUniq(nums []int, v int) []int {
	for _, x := range nums {
		if x == v {
			return nums
		}
	}
	return append(nums, v)
}

func appendUniqStr(arr []string, v string) []string {
	for _, x := range arr {
		if x == v {
			return arr
		}
	}
	return append(arr, v)
}
